colormode: 'color'        # ["color"] or "binary"
hierarchical: 'stacked'   # ["stacked"] or "cutout"
mode: 'none'            # ["spline"] "polygon" or "none"
filter_speckle: 8         # default: 4
color_precision: 7        # default: 6
layer_difference: 5      # default: 16
corner_threshold: 60      # default: 60
length_threshold: 4.0     # in [3.5 10] default: 4.0
max_iterations: 10        # default: 10
splice_threshold: 45      # default: 45
path_precision: 3  